- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf
  when: ansible_distribution == "Archlinux"

- name: Sort mirror by reflector
  shell: reflector --latest 50 --age 24 --sort rate --save /etc/pacman.d/mirrorlist
  when: ansible_distribution == "Archlinux"
